# BIS Standards Data Collector - Source package
from src.version import (
    __version__,
    ENGINE_VERSION,
    RELEASE_ID,
    COLLECTOR_VERSION,
    PARSER_VERSION,
    FORMAT_VERSION,
    SCHEMA_VERSION,
    COLLECTOR_SCHEMA_VERSION,
    GRAPH_SCHEMA_VERSION,
    RECOMMENDATION_RESULT_SCHEMA_VERSION,
    NORMALIZED_REQUIREMENT_SCHEMA_VERSION,
    BENCHMARK_SCHEMA_VERSION,
    REGULATORY_SCHEMA_VERSION,
)
